### Implemenation in Python

**Import modules**

In [1]:
import numpy as np
import pandas as pd
from perceptron import Perceptron

## Perceptron
### Theoretical background

One of the most important models still in use today is the so-called perceptron, whose potential is defined as the weighted sum of incoming signals. If this internal potential of the neuron exceeds its threshold value (defined in our case by the symbol $ϑ$), the neuron is excited to a value of $1$. Otherwise, the neuron is inhibited, which is represented by a value of $0$. Mathematically, this process can be expressed using the signum function in this way:

$$
y = \text{Sgn}\left(\sum_{i=1}^n w_i x_i - \theta\right),
$$

where

$$
\text{Sgn}(x) = \begin{cases} 
1 & \text{if } x > 0, \\
0 & \text{if } x \leq 0.
\end{cases}
$$

By introducing a constant neuron at the input with an excitation state of $x_0 = 1$ and a connection to our neuron $w_0 = -θ$ the previous can be simplified as follows:

$$
y = \text{Sgn}\left(\sum_{i=0}^n w_i x_i\right).
$$

If we analyze the expression in the parentheses such that we set it equal to zero, we obtain the equation of a hyperplane (in the two-dimensional case represented by a line). Thus, using vector notation:
$$
\sum_{i=0}^n w_ix_i = \mathbf{W} \cdot \mathbf{X},
$$
$$
\mathbf{W} \cdot \mathbf{X} = 0.
$$

This plane divides the input space into two half-spaces (see figure). In other words, we are able to use the perceptron to distinguish two classes of inputs. One of them corresponds to an excitation equal to the value 1 and the other to inhibition of the neuron given the value 0. Values $x_1$ and $x_2$ are inputs from the interval $[0, 1]$.

<div style="text-align: center;">
    <img src="perceptron_recognition.png" alt="Perceptron Recognition" style="width: 50%;">
</div>

The question now is how to determine the values of the neuron's weights so that it can correctly recognize (assign to classes) the presented inputs. To achieve this, it is necessary to adapt our perceptron based on a training set through some algorithm. One of the most well-known principles is the adaptation (learning) of the neuron according to Hebb's rule.

**Perceptron learning (Hebb)**
1. Initialization of weights and threshold with random small numbers
   $$w_i(t), (0 \leq i \leq n) \text{ is the weight of input } i \text{ at time } t.$$

2. Presentation of the input and the desired output from the training set
   $$(x_0, x_1, \ldots, x_n) \rightarrow d(t).$$

3. Determination of the actual response
   $$y(t) = \text{Sgn}\left(\sum_{i=0}^n w_i(t)x_i(t)\right).$$

4. Weight Adaptation
   - If the output is correct: $w_i(t+1) = w_i(t)$,
   - If the output is 0 and should have been 1: $w_i(t+1) = w_i(t) + x_i(t)$,
   - If the output is 1 and should have been 0: $w_i(t+1) = w_i(t) - x_i(t)$.

This last step of the algorithm can be modified using a multiplicative factor, which can change the magnitude of changes in adapted weights as follows:

4. Weight adaptation with the learning rate
   - If the output is correct: $w_i(t+1) = w_i(t)$,
   - If the output is 0 and should have been 1: $w_i(t+1) = w_i(t) + \eta x_i(t)$,
   - If the output is 1 and should have been 0: $w_i(t+1) = w_i(t) - \eta x_i(t)$,
   
where $0 \leq \eta \leq 1$ is the learning rate affecting the adaptation process.

If an error of response $\Delta$ is introduced as defined by the difference between the desired and actual outputs:
$$
\Delta = d(t) - y(t),
$$

then we can generalize the weight adaptation by the following prescription:

4. Weight Adaptation with the error of response
$$
\Delta = d(t) - y(t),
$$
$$
w_i(t+1) = w_i(t) + \eta \Delta x_i(t).
$$






**Define training set for wines evaluation**
* Feature 1: sweetness of the wine
* Feature 2: acidity of the wine
* Feature 3: power of wine

Result: 1 good 0 not good

In [2]:
training_set = [
    ([0.0, 1.0, 1.0], [0.0]),
    ([1.0, 0.0, 0.0], [1.0]),
    ([0.5, 0.5, 0.5], [1.0])
]

**Perceptron learning**

In [3]:
perceptron = Perceptron(training_set, 1000)
print("Initial weights: \n", perceptron.weights)
perceptron.learning()
print("Learnt weights: \n", perceptron.weights)


Initial weights: 
 [[ 1.43612461  0.05634323 -0.76593651 -1.00230538]]
Learnt weights: 
 [[-0.06387539  1.10634323 -0.31593651 -0.55230538]]


**Define input vector and run perceptron**

In [4]:
net_input = [1.0, 0.0, 0.0]
output = perceptron.run([net_input])
print("Output for ", net_input, " is ", output)

Output for  [1.0, 0.0, 0.0]  is  [1]


**Save weight matrix on the disk**

In [5]:
np.save('weight_matrix', perceptron.weights)

**Create new perceptron net a set its weights from disk**

In [6]:
perceptron = Perceptron(training_set, 1000)
print("Initial weights: \n", perceptron.weights)
perceptron.weights = np.load('weight_matrix.npy')
print("Learnt weights: \n", perceptron.weights)

Initial weights: 
 [[ 0.91228222 -0.9372091   1.1352477   1.44926008]]
Learnt weights: 
 [[-0.06387539  1.10634323 -0.31593651 -0.55230538]]


**Using Excel Table to define training set**

**Wines Excel file**

In [7]:
data = pd.read_excel('wines.xlsx')
data.head()
training_set = []
for index, row in data.iterrows():
    features = [row['Sweetness'], row['Acidity'], row['Power']]
    result = [row['Good']]
    training_set.append((features, result))
#print("Transformations: ", training_set)
training_set



[([0.0, 1.0, 1.0], [0.0]), ([1.0, 0.0, 0.0], [1.0]), ([0.5, 0.5, 0.5], [1.0])]

**Diagnosis learning verification**

Training set consist of several patients, where symptoms are associates with diagnosis. The goal is to learn from this examples.

In [8]:
data = pd.read_excel('diagnosis.xlsx')
data.head()
training_set = []
for index, row in data.iterrows():
    features = [row['Fever'], row['Cough'], row['Headache'], row['Tiredness'], row['Night Sweat']]
    result = [row['Pneumonia'], row['Flu'], row['Cold']]
    training_set.append((features, result))

perceptron = Perceptron(training_set, 1000)
perceptron.learning()

for row in training_set:
    net_input = row[0]
    net_output = perceptron.run(net_input)
    print("Input: ", net_input, " Output: ", net_output)

header = list(data.columns)
 

Input:  [0.0, 0.5, 0.5, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 1.0, 1.0, 1.0, 0.0]  Output:  [0, 1, 0]
Input:  [0.5, 1.0, 0.0, 1.0, 1.0]  Output:  [1, 0, 0]
Input:  [0.0, 0.5, 0.0, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 0.5, 1.0, 0.5, 0.0]  Output:  [0, 1, 0]
Input:  [1.0, 1.0, 0.0, 0.5, 0.5]  Output:  [1, 0, 0]


**Usage of diagnosis app**

Input data are read from excel file and diagosis is inferred from the learnt net o perceptrons.

In [9]:
input_data = pd.read_excel('diagnosis_input.xlsx')
input_data.head()
input_set = []
for index, row in input_data.iterrows():
    features = [row['Fever'], row['Cough'], row['Headache'], row['Tiredness'], row['Night Sweat']]
    input_set.append(features)

output_set = []
for net_input in input_set:
    net_output = perceptron.run(net_input)
    output_set.append(net_output)
    print("Input: ", net_input, " Output: ", net_output)
# Create a DataFrame for the output data

header = list(data.columns)
output_data = pd.DataFrame(columns=header)

for i in range(len(input_set)):
    row = input_set[i] + output_set[i]
    output_data.loc[i] = row

output_data.to_excel('diagnosis_output.xlsx', index=False)
output_data



Input:  [0.0, 0.5, 0.0, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 1.0, 1.0, 1.0, 0.0]  Output:  [0, 1, 0]
Input:  [0.5, 1.0, 0.0, 1.0, 1.0]  Output:  [1, 0, 0]
Input:  [1.0, 0.5, 0.5, 0.5, 0.0]  Output:  [0, 0, 0]
Input:  [0.0, 0.5, 0.0, 0.2, 0.0]  Output:  [0, 0, 0]


Fever  Cough  Headache  Tiredness  Night Sweat  Pneumonia  Flu  Cold
0    0.0    0.5       0.0        0.0          0.0        0.0  0.0   1.0
1    1.0    1.0       1.0        1.0          0.0        0.0  1.0   0.0
2    0.5    1.0       0.0        1.0          1.0        1.0  0.0   0.0
3    1.0    0.5       0.5        0.5          0.0        0.0  0.0   0.0
4    0.0    0.5       0.0        0.2          0.0        0.0  0.0   0.0

**Mean squared error for the training set**

In [10]:
mse = perceptron.calculate_mse()
mse

0.0

### Max error of a single neuron withing the complete training set

In [11]:
max = perceptron.calculate_max()
max

0